add homework-8
pavelchamgl/homework_nhs pull request #2
Opened 2022-11-23 09:52 UTC by pavelchamgl

2022-11-24 05:58 UTC, nikitapt63 requested changes

2022-11-24 05:58 UTC, nikitapt63 commented on Task_8/Task_8.py
> +    return "".join(map(str.title, result))
Все окей, только первое слово должно быть с маленькой буквы

2022-12-01 10:15 UTC, pavelchamgl reviewed
Исправил эту функцию

2022-12-02 05:40 UTC, nikitapt63 approved these changes

2022-12-02 06:04 UTC, merged