add homework_14
pavelchamgl/homework_nhs pull request #8
Opened 2022-12-18 17:02 UTC by pavelchamgl

2022-12-18 19:08 UTC, nikitapt63 requested changes

2022-12-18 19:08 UTC, nikitapt63 commented on task_14/task_14.py
> +        return Car.count
это должен быть @classmethod

2022-12-18 19:11 UTC, nikitapt63 commented on task_14/task_14.py
> +        return Car.count
+ Еще нужен дочерний класс

2022-12-18 20:35 UTC, pavelchamgl commented on task_14/task_14.py
> +        return Car.count
Ниже у меня есть **class CarHonda(Car):** - он не является дочерним классом?

2022-12-19 05:50 UTC, nikitapt63 approved these changes

2022-12-19 17:47 UTC, merged